export const AUTHENTICATION_INIT = "AUTHENTICATION_INIT";
export const AUTHENTICATION_FAILED = "AUTHENTICATION_FAILED";
export const AUTHENTICATION_SUCCESS = "AUTHENTICATION_SUCCESS";
export const AUTHENTICATION_LOGOUT = "AUTHENTICATION_LOGOUT";

export const PAGE_RELOAD = "PAGE_RELOAD";

//Products

export const SYNC_PRODUCT_INIT = "SYNC_PRODUCT_INIT";
export const SYNC_PRODUCT_START = "SYNC_PRODUCT_START";
export const SYNC_PRODUCT_SUCCESS = "SYNC_PRODUCT_SUCCESS";
export const SYNC_PRODUCT_FAILED = "SYNC_PRODUCT_FAILED";

export const ADD_PRODUCT_INIT = "ADD_PRODUCT";
export const ADD_PRODUCT_SUCCESS = "ADD_PRODUCT_SUCCESS";
export const ADD_PRODUCT_FAILED = "ADD_PRODUCT_FAILED";

//Stock - RawMaterial
export const SYNC_STOCK_INIT = "SYNC_STOCK_INIT";
export const SYNC_STOCK_START = "SYNC_STOCK_START";
export const SYNC_STOCK_FAILED = "SYNC_STOCK_FAILED";
export const SYNC_STOCK_SUCCESS = "SYNC_STOCK_SUCCESS";

export const STOCK_UPDATE_START = "STOCK_UPDATE_START";
export const STOCK_UPDATE_SUCCESS = "STOCK_UPDATE_SUCCESS";
export const STOCK_UPDATE_FAILED = "STOCK_UPDATE_FAILED";

export const ADD_NEW_STOCK_START = "ADD_NEW_STOCK_START";
export const ADD_NEW_STOCK_FAILED = "ADD_NEW_STOCK_FAILED";
export const ADD_NEW_STOCK_SUCCESS = "ADD_NEW_STOCK_SUCCESS";

export const DELETE_STOCK_START = "DELETE_STOCK_START";
export const DELETE_STOCK_SUCCESS = "DELETE_STOCK_SUCCESS";
export const DELETE_STOCK_FAILED = "DELETE_STOCK_FAILED";

export const PRODUCT_RAWMATERIAL_START = "PRODUCT_RAWMATERIAL_START";
export const PRODUCT_RAWMATERIAL_SUCCESS = "PRODUCT_RAWMATERIAL_SUCCESS";
export const PRODUCT_RAWMATERIAL_FAILED = "PRODUCT_RAWMATERIAL_FAILED";

export const PRODUCT_BATCH_RECORD_SUCCESS = "PRODUCT_BATCH_RECORD_SUCCESS";
export const PRODUCT_BATCH_RECORD_FAILED = "PRODUCT_BATCH_RECORD_FAILED";
